source 'https://rubygems.org'

gem 'rails', '3.2.3'

gem 'jquery-rails'

#gem 'fluidfeatures-rails', :path => '../../../fluidfeatures-rails'
gem 'fluidfeatures-rails', :git => 'git://github.com/BigFastSite/fluidfeatures-rails.git'

